baseURL = 'https://thebenswift.com/'
languageCode = 'en-us'
title = 'ben swift - 班傑明'
theme = "papermod"
[menu]
  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "example"
    name = "example.org"
    url = "https://example.org"
    weight = 30
    
[params]
  [params.homeInfoParams]
    Title = "Hi there wave"
    Content = "Can be Info, links, about..."

  [[params.socialIcons]]
    name = "<platform>"
    url = "<link>"

  [[params.socialIcons]]
    name = "<platform 2>"
    url = "<link2>"